#!/usr/bin/env node
/**
 * Spec 250 phase 11 — the rebase drill, as a PROCEDURE rather than an event.
 *
 * ## What it proves, and what it deliberately does not
 *
 * Criterion 9 asks whether the customization can be carried onto a later
 * upstream: whether the rebase completes, whether the contract regenerates from
 * the rebased fork, and whether `shape-check` still holds. It is met **by this
 * running and reporting**, not by adopting a new base.
 *
 * The drill answers the first question by running it and the second by measuring
 * its inputs. It does NOT answer the third, and the section below says so in the
 * place a reader would otherwise assume it did.
 *
 * ## Nothing real moves. That is the point, and it was ruled.
 *
 *   `/Users/chris/dev/t3code`       the PRESERVED upstream clone. Read-only.
 *                                   Fetch is fine — remote-tracking refs move
 *                                   and HEAD does not. A checkout is not.
 *   `/Users/chris/dev/t3code-codev` the fork. Read-only here.
 *   `pin.json`                      NOT advanced.
 *
 * The moment `pin.json` names a new base, `verify-upstream` expects the
 * preserved clone to BE there, and every spec 146 and spec 236 result tied to
 * `082e6ea52186` stops being re-runnable. Advancing the base is a decision taken
 * when there is a reason — a security fix, a feature we need — never as a phase
 * deliverable. So the drill runs in a **scratch clone** and throws it away.
 *
 * ## Every failure is reported, and the kinds are kept apart
 *
 * A drill that cannot run and a drill that ran and found conflicts are different
 * facts wanting different next actions, and reporting the first as the second
 * would be this project's recurring defect on the one tool whose job is to say
 * what happened. So:
 *
 *   ok                 every customization commit replayed with no conflicts
 *   conflicts          the rebase stopped on conflicts. THIS IS A RESULT, not an
 *                      error — it is the number the drill exists to produce, and
 *                      the files are listed
 *   could-not-run      no scratch, no clone, no upstream target. NOTHING was
 *                      learned, and it must never read as "no conflicts"
 *
 * ## What `ok` does NOT say, and why the vocabulary is exactly three words
 *
 * An earlier draft of this header defined `ok` as "rebase clean, contract
 * regenerated, shape-check held" and listed `regenerate-failed` and
 * `shape-check-failed` beside it. At the time the drill ran neither step, and
 * neither outcome was ever assigned anywhere in this file. The contract was
 * described as regenerated by a comment rather than by a generator — this
 * project's own recurring defect, a claim spelled the same way whether or not
 * anything checked it, sitting on the one tool whose subject is that
 * distinction.
 *
 * The drill regenerates now (see below), and the vocabulary is STILL three
 * words, deliberately. `outcome` describes the REBASE. A contract that
 * regenerates into something different is not a failed rebase, it is the cost of
 * adopting the base — so it is reported in `contractRegeneration` with the
 * artifact list, exactly as `conflicts` reports the file list. A test holds the
 * documented set and the assignable set together, so this cannot drift again.
 *
 * ## Regeneration IS proved, in the throwaway, and here is why that needed a
 * ## second scratch rather than the obvious call
 *
 * `generate.mjs` refuses any checkout whose `HEAD` is not `pin.commit`, and no
 * rebased tree can satisfy that: its head is a commit that did not exist before
 * the rebase. Pointed at the real repository, "regenerate from the rebased tree"
 * therefore means moving the real pin, which is the adoption this drill exists in
 * order NOT to perform. That is why the first version of this file only measured
 * the generator's INPUTS and said, correctly, that shape-check had not run.
 *
 * It leaves criterion 9 proving that the rebase measures, not that the contract
 * still regenerates after one — and the second is the claim that matters on the
 * day a new base is adopted, which is the worst possible moment to find out it
 * does not hold. So the drill now proves it, without touching anything real:
 *
 *   1. `git merge-tree --write-tree` writes the merged tree as an object, and
 *      `git commit-tree` makes it a commit IN THE THROWAWAY CLONE. Conflicted
 *      files carry markers; none of them is in the closure, and if one ever is,
 *      the generator fails and that failure is the reported result.
 *   2. A SCRATCH CODEGEN ROOT is assembled beside it: `generate.mjs` resolves
 *      every path from its own location, so a copy of the tool under a scratch
 *      directory reads a scratch `pin.json` and writes to a scratch
 *      `generated/`. The scratch pin names the merged commit, so the guard is
 *      satisfied honestly rather than bypassed.
 *   3. The generator runs. Then its output is compared, byte for byte, to the
 *      artifacts actually vendored in this repository.
 *
 * The real `pin.json` is not written and not read for this. Both real checkouts
 * are untouched, and the read-only order is still re-checked afterwards.
 *
 * A regenerated contract that DIFFERS is a result, not a failure — the same
 * argument as `conflicts`. It is the answer to "what would adopting this base
 * cost", and it is reported with the artifact list rather than as an error.
 *
 * `contractRegeneration.attempted` is `false`, with a reason, whenever there was
 * no tree to generate from — and `could-not-run` carries none of these fields at
 * all, deliberately: it means NOTHING was learned, so a measurement-shaped field
 * on it would be the first thing a reader mistook for a finding.
 *
 * ## The interpreter is not inherited from PATH
 *
 * The generator imports the closure's TypeScript directly and needs Node's type
 * stripping, so **Node 22 or newer**. The drill itself runs fine under 20. When
 * the interpreter cannot run the generator this reports `attempted: false` with
 * `NO_INTERPRETER` — never "the contract does not regenerate", which is a claim
 * about the fork rather than about this machine. `T3_CODEGEN_NODE` overrides.
 *
 * Usage:
 *   node tools/t3-fork/rebase-drill.mjs [--onto <ref>] [--out <file>] [--keep]
 *
 * `--onto` defaults to the upstream clone's `origin/main`. `--keep` leaves the
 * scratch for inspection and prints where it is.
 *
 * Exit codes: 0 ok or conflicts (both are results), 3 could-not-run.
 */

import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import {
  cpSync, existsSync, mkdtempSync, mkdirSync, readdirSync, readFileSync, rmSync, symlinkSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { closureMeasurability } from './drill-closure.mjs';
import { resolveIdentities } from './identities.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..', '..');
const pinPath = join(repoRoot, 'packages', 'types', 'src', 't3', 'pin.json');
const pin = JSON.parse(readFileSync(pinPath, 'utf8'));
const identities = resolveIdentities(pin);

const COULD_NOT_RUN = 3;

/** Upstream's numbered migration registry, read from both refs. */
const MIGRATIONS_DIR = 'apps/server/src/persistence/Migrations';

/** The generator's own inputs, as repository paths. Derived once, read in three places. */
const closurePaths = pin.closure.map((file) => `${pin.contractsRoot}/${file}`);

/** Where the vendored contract records the bytes it was generated from. */
const vendoredHashPath = join(
  repoRoot, 'packages', 'types', 'src', 't3', 'generated', 'source-hash.json',
);

const argv = process.argv.slice(2);
const flag = (name, fallback = undefined) => {
  const i = argv.indexOf(`--${name}`);
  return i >= 0 ? argv[i + 1] : fallback;
};
const keep = argv.includes('--keep');
const outPath = flag('out');

function run(cwd, ...args) {
  return execFileSync('git', ['-C', cwd, ...args], { encoding: 'utf8', maxBuffer: 128 * 1024 * 1024 });
}

/** `git` that reports its failure instead of throwing an opaque status. */
function tryRun(cwd, ...args) {
  try {
    return { ok: true, out: run(cwd, ...args) };
  } catch (error) {
    return {
      ok: false,
      out: `${error.stdout ?? ''}${error.stderr ?? ''}`.trim() || String(error.message ?? error),
    };
  }
}

/**
 * `git rev-list --count`, with "could not count" spelled differently from zero.
 *
 * A range that cannot be read and a range with nothing in it are the two answers
 * this whole file is organised around keeping apart, and `Number('')` is 0.
 */
function countCommits(root, from, to, paths) {
  const args = ['rev-list', '--count', `${from}..${to}`];
  if (paths) args.push('--', ...paths);
  const counted = tryRun(root, ...args);
  if (!counted.ok) return null;
  const n = Number(counted.out.trim());
  return Number.isFinite(n) ? n : null;
}

/**
 * THE CLOSURE AS THE REBASED TREE WOULD HAND IT TO THE GENERATOR.
 *
 * Hashed the way `generate.mjs` hashes it (sha256 per closure file, keyed by the
 * name it uses) and compared to `generated/source-hash.json` — the layer that
 * file itself names as the load-bearing drift detector, because the emitted
 * schema is blind to constraints behind a `decodeTo` transform and a relaxed
 * branded id moves not one byte of it.
 *
 * So this answers "would the rebased tree regenerate the contract we vendored,
 * and if not, which of the generator's inputs moved" — which is as far as the
 * drill can go without running the generator, and it must not be read as further
 * than that. `checked: false` carries a reason and is never a pass.
 *
 * MUST be called while the merged tree is still on disk. After `merge --abort`
 * the worktree is the fork again and this compares the fork to itself, which is
 * a tautology that always reports zero moved files.
 */
function closureSourceHash(tree) {
  let vendored;
  try {
    vendored = JSON.parse(readFileSync(vendoredHashPath, 'utf8'));
  } catch (error) {
    return {
      checked: false,
      reason: `generated/source-hash.json could not be read (${error.message ?? error}), so there `
        + 'is nothing to compare the rebased closure against. Nothing is claimed about whether it '
        + 'moved.',
    };
  }
  const files = {};
  const unreadable = [];
  for (const file of pin.closure) {
    const path = join(tree, pin.contractsRoot, file);
    if (!existsSync(path)) {
      unreadable.push(file);
      continue;
    }
    files[file] = createHash('sha256').update(readFileSync(path)).digest('hex');
  }
  if (unreadable.length > 0) {
    return {
      checked: false,
      unreadable,
      reason: `the merged tree has no ${unreadable.join(', ')} under ${pin.contractsRoot}. The `
        + 'generator would not find its own source there, and that is not "the contract is '
        + 'unchanged".',
    };
  }
  const moved = pin.closure.filter((file) => files[file] !== vendored.files?.[file]);
  return {
    checked: true,
    algorithm: 'sha256',
    comparedTo: vendored.commit ?? null,
    files,
    moved,
    detail: moved.length === 0
      ? 'every file the generator reads is byte-identical after the merge, so the rebased tree '
        + 'regenerates the contract already vendored. What the generator actually emitted is '
        + 'contractRegeneration; this is its input.'
      : `${moved.length} of ${pin.closure.length} closure files differ after the merge: `
        + `${moved.join(', ')}. The generator therefore reads different bytes; WHAT it emits from `
        + 'them is contractRegeneration, which runs it rather than predicting.',
  };
}

/** Where the vendored artifacts live, and the interpreter the generator needs. */
const generatedDir = join(repoRoot, 'packages', 'types', 'src', 't3', 'generated');
const CODEGEN_MIN_MAJOR = 22;

/**
 * Files whose bytes name the commit they were generated from, so they differ
 * after ANY rebase regardless of whether a shape moved. Named rather than
 * filtered out: `source-hash.json` also carries the closure hashes, which is a
 * real signal, so a reader must be able to see it in the list AND know part of
 * its diff is identity.
 */
const EMBEDS_COMMIT_ID = ['ATTRIBUTION.md', 'source-hash.json'];

/** The artifacts that describe SHAPES Codev consumes. Drift here is the finding. */
const SHAPE_ARTIFACTS = ['schema.json', 'schema.ts', 'types.d.ts', 'methods.json'];

/**
 * The interpreter that will run the generator, or a stated refusal.
 *
 * The fork harness already refuses to inherit its server Node from PATH for the
 * same reason: an interpreter that cannot run the tool produces an error that
 * reads exactly like the tool reporting bad news about the code.
 */
function codegenInterpreter() {
  const bin = process.env.T3_CODEGEN_NODE ?? process.execPath;
  const asked = tryRun2(bin, ['--version']);
  if (!asked.ok) {
    return { ok: false, reason: `NO_INTERPRETER: ${bin} could not be run (${asked.out}).` };
  }
  const major = Number(/^v(\d+)/.exec(asked.out.trim())?.[1] ?? NaN);
  if (!Number.isFinite(major) || major < CODEGEN_MIN_MAJOR) {
    return {
      ok: false,
      reason: `NO_INTERPRETER: the generator imports the closure's TypeScript and needs Node `
        + `>=${CODEGEN_MIN_MAJOR}; ${bin} is ${asked.out.trim()}. Set T3_CODEGEN_NODE. This says `
        + 'nothing about whether the contract regenerates — it says this machine did not ask.',
    };
  }
  return { ok: true, bin, version: asked.out.trim() };
}

/** `execFileSync` for a non-git binary, reporting failure rather than throwing. */
function tryRun2(bin, args, env) {
  try {
    return {
      ok: true,
      out: execFileSync(bin, args, {
        encoding: 'utf8', maxBuffer: 64 * 1024 * 1024, env: { ...process.env, ...env },
      }),
    };
  } catch (error) {
    return {
      ok: false,
      out: `${error.stdout ?? ''}${error.stderr ?? ''}`.trim() || String(error.message ?? error),
    };
  }
}

/**
 * REGENERATE THE CONTRACT FROM THE REBASED TREE, IN A SECOND THROWAWAY.
 *
 * `generate.mjs` resolves `pin.json`, its output directory and its staging area
 * from its own file location, so a COPY of the tool under a scratch root reads a
 * scratch pin and writes to a scratch `generated/`. The scratch pin names the
 * merged commit, which satisfies the `HEAD === pin.commit` guard honestly instead
 * of bypassing it — the guard's purpose is that artifacts are reproducible from
 * the commit they name, and here they are.
 *
 * `node_modules` is symlinked rather than copied: it is the only part that is
 * large, it is read-only to the generator, and Node resolves through the link.
 *
 * @returns the `contractRegeneration` block, whatever happened.
 */
function regenerateFrom({ scratch, forkTree, commit, sourceKind }) {
  const interpreter = codegenInterpreter();
  if (!interpreter.ok) return { attempted: false, reason: interpreter.reason };

  const root = join(scratch, 'codegen-root');
  const outDir = join(root, 'packages', 'types', 'src', 't3', 'generated');
  try {
    mkdirSync(join(root, 'tools', 't3-codegen'), { recursive: true });
    mkdirSync(join(root, 'tools', 't3-fork'), { recursive: true });
    mkdirSync(outDir, { recursive: true });
    for (const file of ['generate.mjs', 'package.json']) {
      cpSync(join(repoRoot, 'tools', 't3-codegen', file), join(root, 'tools', 't3-codegen', file));
    }
    symlinkSync(
      join(repoRoot, 'tools', 't3-codegen', 'node_modules'),
      join(root, 'tools', 't3-codegen', 'node_modules'),
    );
    cpSync(join(repoRoot, 'tools', 't3-fork', 'identities.mjs'),
      join(root, 'tools', 't3-fork', 'identities.mjs'));
    writeFileSync(
      join(root, 'packages', 'types', 'src', 't3', 'pin.json'),
      `${JSON.stringify({ ...pin, commit }, null, 2)}\n`,
    );
  } catch (error) {
    return {
      attempted: false,
      reason: `the scratch codegen root could not be assembled (${error.message ?? error}). `
        + 'Nothing is claimed about whether the contract regenerates.',
    };
  }

  const ran = tryRun2(interpreter.bin, [join(root, 'tools', 't3-codegen', 'generate.mjs')], {
    T3CODE_FORK_ROOT: forkTree,
    T3CODE_ROOT: identities.upstream.root,
  });
  if (!ran.ok) {
    return {
      attempted: true,
      source: { commit, kind: sourceKind },
      generated: false,
      generatorSaid: ran.out.split('\n').slice(0, 12).join('\n'),
      detail: 'the generator did not complete against the rebased tree. That is the answer, and '
        + 'it is a different answer from "the contract changed".',
    };
  }

  /*
   * Compared to what is VENDORED IN THIS REPOSITORY, not to what the scratch run
   * wrote a moment ago. Comparing a run to itself is the tautology this whole
   * file is organised around refusing.
   */
  const differing = [];
  for (const name of readdirSync(outDir)) {
    const mine = join(outDir, name);
    const theirs = join(generatedDir, name);
    if (!existsSync(theirs)) { differing.push(name); continue; }
    if (readFileSync(mine, 'utf8') !== readFileSync(theirs, 'utf8')) differing.push(name);
  }
  const shapesDiffering = differing.filter((f) => SHAPE_ARTIFACTS.includes(f));
  const identityBearing = differing.filter((f) => EMBEDS_COMMIT_ID.includes(f));

  return {
    attempted: true,
    source: { commit, kind: sourceKind },
    method: 'a scratch pin naming the merged commit, in a scratch copy of the codegen tool. The '
      + 'real pin.json was neither read nor written for this, and both real checkouts are '
      + 'untouched.',
    interpreter: interpreter.version,
    generated: true,
    shapeCheckHolds: shapesDiffering.length === 0,
    artifactsDiffering: differing,
    shapesDiffering,
    embedsCommitId: identityBearing,
    /*
     * generate.mjs's own dangerous case, restated here because this is the other
     * place it can occur: the source moved and the emitted schema did not, which
     * is NOT "no effect" — every branded id in the contract emits unconstrained,
     * so a relaxed constraint lands here with a zero-byte schema diff.
     */
    hashMovedShapesDidNot: differing.includes('source-hash.json') && shapesDiffering.length === 0,
    detail: shapesDiffering.length === 0
      ? 'the contract regenerates from the rebased tree and the shapes Codev consumes are '
        + 'unchanged.'
      : `the contract regenerates, and ${shapesDiffering.length} shape artifact`
        + `${shapesDiffering.length === 1 ? '' : 's'} would change: ${shapesDiffering.join(', ')}. `
        + 'That is what adopting this base costs, measured rather than predicted.',
  };
}

/**
 * NOT DONE, AND SAID SO IN EVERY RESULT.
 *
 * An absent field reads as "nobody thought about it". This is a stated refusal
 * with its reason, so a later reader asking "did shape-check run" gets an answer
 * from the evidence rather than from the absence of one.
 */
const NO_TREE_TO_REGENERATE_FROM = {
  attempted: false,
  reason: 'nothing was rebased and nothing was merged, so there is no tree to generate a contract '
    + 'from. Vacuous rather than skipped, and it is not "the contract does not regenerate".',
};

/**
 * The merged tree as a COMMIT in the throwaway clone.
 *
 * `git merge-tree --write-tree` writes the merge as an object even when files
 * conflict — conflicted paths get markers — so a tree exists to generate from
 * whether or not the sequential rebase completed. `commit-tree` gives it the
 * identity the generator's pin guard needs. Both real checkouts are untouched;
 * this writes objects into the scratch clone and nothing else.
 */
function mergedTreeCommit(clone, forkHead, target) {
  const tree = tryRun(clone, 'merge-tree', '--write-tree', forkHead, target);
  const sha = tree.out.split('\n')[0].trim();
  if (!/^[0-9a-f]{40}$/.test(sha)) {
    return { ok: false, reason: `git merge-tree wrote no tree (${tree.out.split('\n')[0]}).` };
  }
  const committed = tryRun(
    clone, 'commit-tree', sha, '-p', forkHead, '-p', target, '-m', 'spec 250 drill: merged tree',
  );
  if (!committed.ok) return { ok: false, reason: `git commit-tree failed (${committed.out}).` };
  const commit = committed.out.trim();
  const checkedOut = tryRun(clone, 'checkout', '--quiet', '--detach', commit);
  if (!checkedOut.ok) return { ok: false, reason: `could not check out the merged tree (${checkedOut.out}).` };
  return { ok: true, commit };
}

function report(result) {
  const body = JSON.stringify(result, null, 2);
  if (outPath) {
    mkdirSync(dirname(resolve(repoRoot, outPath)), { recursive: true });
    writeFileSync(resolve(repoRoot, outPath), `${body}\n`);
    console.error(`[rebase-drill] written to ${outPath}`);
  }
  console.log(body);
  process.exit(result.outcome === 'could-not-run' ? COULD_NOT_RUN : 0);
}

const upstreamRoot = identities.upstream.root;
const forkRoot = identities.fork.root;

for (const [label, root] of [['upstream', upstreamRoot], ['fork', forkRoot]]) {
  if (!existsSync(root)) {
    report({
      outcome: 'could-not-run',
      reason: `no ${label} checkout at ${root}. Nothing was rebased, and that is not the same as `
        + 'a rebase with no conflicts.',
    });
  }
}

// The target, read from the PRESERVED clone's remote-tracking ref. `--onto` may
// name any resolvable ref; an unresolvable one is could-not-run, never zero.
const onto = flag('onto', 'origin/main');
const ontoSha = tryRun(upstreamRoot, 'rev-parse', '--verify', '--quiet', `${onto}^{commit}`);
if (!ontoSha.ok) {
  report({
    outcome: 'could-not-run',
    reason: `${onto} does not resolve in ${upstreamRoot}. Fetch first — a ref that cannot be read `
      + 'is "unknown", not "unchanged".',
  });
}
const target = ontoSha.out.trim();
const base = identities.fork.base;
const forkHead = run(forkRoot, 'rev-parse', 'HEAD').trim();

if (target === base) {
  // A legitimate zero, and it is a PASS — but it is reported as its own outcome
  // so it can never be confused with a drill that did not run.
  report({
    outcome: 'ok',
    signal: 'NO_UPSTREAM_MOVEMENT',
    detail: `${onto} is still ${base.slice(0, 12)}; there is nothing to rebase onto. The procedure `
      + 'ran and had nothing to do, which is different from the procedure not running.',
    /*
     * SAID OUT LOUD RATHER THAN LEFT ABSENT.
     *
     * This path skips the watermark check, and it is right to: with no upstream
     * movement there are no new migrations, so the check would be vacuous. But a
     * result whose `watermark` field is simply MISSING looks identical to a run
     * where the check failed to happen for some other reason — and the evidence
     * test asserts `checked: true`, so a silent absence would surface as a
     * confusing test failure rather than as this fact.
     */
    watermark: {
      checked: false,
      reason: 'no upstream movement, so no migrations arrived and there was nothing to check. '
        + 'Vacuous rather than skipped.',
    },
    /* Same reasoning: no scratch clone was made, so there was no merged tree to hash. */
    contractClosure: {
      files: closurePaths,
      checked: false,
      reason: 'nothing was rebased, so there is no merged tree whose closure could be hashed. '
        + 'Vacuous rather than skipped.',
    },
    contractRegeneration: NO_TREE_TO_REGENERATE_FROM,
    upstreamChurn: { range: `${base.slice(0, 12)}..${target.slice(0, 12)}`, commits: 0, closureTouching: 0 },
    upstreamRoot, forkRoot, base, target, forkHead,
  });
}

const scratch = mkdtempSync(join(tmpdir(), 'spec-250-rebase-drill-'));
const clone = join(scratch, 'fork');
const started = new Date().toISOString();
let result;

try {
  /*
   * Cloned from the LOCAL fork with `--shared`, and upstream added as a LOCAL
   * remote. Both are reads. The drill never touches the network and never writes
   * to either real checkout — a scratch that fetched from GitHub would also be
   * measuring the network.
   */
  run(scratch, 'clone', '--quiet', '--shared', '--no-checkout', forkRoot, clone);
  run(clone, 'remote', 'add', 'preserved-upstream', upstreamRoot);
  run(clone, 'fetch', '--quiet', 'preserved-upstream', target);
  run(clone, 'checkout', '--quiet', '--detach', forkHead);

  const carried = run(clone, 'rev-list', '--count', `${base}..${forkHead}`).trim();

  const rebase = tryRun(clone, '-c', 'rebase.autoStash=false', 'rebase', '--onto', target, base, forkHead);

  if (!rebase.ok) {
    /*
     * CONFLICTS ARE THE RESULT, NOT THE ERROR. This is the number the drill
     * exists to produce, so it is reported with the files rather than as a
     * failure — and the drill exits 0, because it ran.
     */
    const conflicted = tryRun(clone, 'diff', '--name-only', '--diff-filter=U');
    const stopped = tryRun(clone, 'rev-parse', '--short', 'REBASE_HEAD');
    // Aborted BEFORE the whole-surface probe below: a merge started mid-rebase
    // would be measuring a half-replayed tree, which is neither of the two
    // questions being asked.
    tryRun(clone, 'rebase', '--abort');
    result = {
      outcome: 'conflicts',
      detail: 'the rebase stopped on conflicts. That is a measurement, not a failure — it is what '
        + 'the drill is for.',
      conflictedFiles: conflicted.ok ? conflicted.out.trim().split('\n').filter(Boolean) : [],
      stoppedAt: stopped.ok ? stopped.out.trim() : null,
      gitSaid: rebase.out.split('\n').slice(0, 20),
    };
    /*
     * AND THE WHOLE SURFACE, IN ONE PASS.
     *
     * `git rebase` is sequential and stops at the FIRST conflict, so "stopped at
     * commit 6 of 42" answers "where does it stop" and not "how much conflicts" —
     * and reporting only the first would understate the drill every time. A
     * three-way merge of the same two trees surfaces every conflicting file at
     * once.
     *
     * It is a MEASUREMENT, not the procedure: the real rebase is still what an
     * operator runs, and this number is how big that job is before they start.
     * Nothing is resolved here and nothing is committed.
     */
    const merge = tryRun(clone, 'merge', '--no-commit', '--no-ff', target);
    const allConflicts = tryRun(clone, 'diff', '--name-only', '--diff-filter=U');
    const conflictedList = allConflicts.ok
      ? allConflicts.out.trim().split('\n').filter(Boolean)
      : [];
    const closureConflicts = conflictedList.filter((file) => closurePaths.includes(file));
    /*
     * Hashed HERE, off the merged worktree, BEFORE the abort. After the abort the
     * tree is the fork again and the comparison becomes the fork against itself —
     * a tautology that reports zero moved files on every run, forever.
     *
     * Whether the comparison is possible at all is decided in `drill-closure.mjs`
     * rather than inline. Its second case — a merge that neither completed nor
     * conflicted — is not reachable from any normal run, so asserting it here
     * would be asserting it where no test can get to it. It lives in a module a
     * unit test can import; this file is a script, and importing it runs a drill.
     */
    const measurable = closureMeasurability({
      mergeOk: merge.ok,
      conflictedFiles: conflictedList,
      closureConflicts,
      gitSaid: merge.out,
    });
    const mergedSourceHash = measurable.measurable
      ? closureSourceHash(clone)
      : { checked: false, reason: measurable.reason };
    tryRun(clone, 'merge', '--abort');
    result.wholeSurface = {
      method: 'three-way merge of the same two trees, aborted immediately',
      clean: merge.ok,
      conflictedFiles: conflictedList,
    };

    /*
     * IS THE CONTRACT REACHABLE AFTER THE REBASE?
     *
     * The plan asks the drill to regenerate the contract from the rebased fork
     * and pass shape-check. That is only reachable if the generator's SOURCE —
     * the pinned closure — comes through the rebase without conflicts, so this
     * answers the prerequisite rather than asserting the conclusion.
     *
     * Reported as its own field because "the customization conflicts somewhere"
     * and "the contract cannot be regenerated" are different sizes of problem:
     * the first is three files an operator resolves, the second would mean the
     * vendored contract is stranded until they do.
     */
    result.contractClosure = {
      files: closurePaths,
      conflicted: closureConflicts,
      regenerationReachable: closureConflicts.length === 0,
      sourceHash: mergedSourceHash,
      detail: closureConflicts.length === 0
        ? 'every file the generator reads merged without conflict, so regenerating the contract '
          + 'from the rebased tree is not blocked by the rebase. What the regenerated contract '
          + 'would CHANGE is bounded by sourceHash.moved and settled by classify-churn '
          + '--upstream-movement.'
        : 'the generator\'s own source conflicts, so the vendored contract cannot be regenerated '
          + 'until those are resolved.',
    };

    /*
     * AND NOW ACTUALLY REGENERATE, from the merged tree written by git rather
     * than by me. The sequential rebase stopped, so there is no rebased HEAD —
     * but the generator reads only the closure, and the closure merged clean.
     * The merge-tree commit is that merge, given an identity.
     */
    const merged = mergedTreeCommit(clone, forkHead, target);
    result.contractRegeneration = merged.ok
      ? regenerateFrom({
        scratch,
        forkTree: clone,
        commit: merged.commit,
        sourceKind: 'the three-way merge of the same two trees, written by git merge-tree. '
          + 'Conflicted paths carry markers; none of them is in the contract closure.',
      })
      : { attempted: false, reason: merged.reason };
  } else {
    const rebasedHead = run(clone, 'rev-parse', 'HEAD').trim();
    const rebasedCount = run(clone, 'rev-list', '--count', `${target}..${rebasedHead}`).trim();
    result = {
      outcome: 'ok',
      detail: `all ${carried} customization commits replayed onto ${target.slice(0, 12)} with no `
        + 'conflicts. That is what `ok` means here, and all it means — what the regenerated '
        + 'contract looks like is contractRegeneration, reported separately because a moved '
        + 'contract is a result rather than a failed rebase.',
      rebasedHead,
      commitsCarried: Number(carried),
      commitsAfterRebase: Number(rebasedCount),
      /*
       * Reported on this branch too. It used to be set only where the rebase
       * conflicted, so the one outcome that CLAIMED the contract was fine was
       * also the one that measured nothing about it.
       */
      contractClosure: {
        files: closurePaths,
        conflicted: [],
        regenerationReachable: true,
        sourceHash: closureSourceHash(clone),
        detail: 'the rebase replayed every commit, so the generator would read its source from '
          + 'the rebased tree exactly as it reads it from the fork today. Whether that source '
          + 'still produces the vendored contract is sourceHash, not an assumption.',
      },
      /* The rebased tree itself — no merge-tree needed, the worktree is already it. */
      contractRegeneration: regenerateFrom({
        scratch,
        forkTree: clone,
        commit: rebasedHead,
        sourceKind: 'the rebased tree itself; every customization commit replayed cleanly.',
      }),
    };
  }

  result = {
    ...result,
    startedAt: started,
    finishedAt: new Date().toISOString(),
    contractRegeneration: result.contractRegeneration ?? NO_TREE_TO_REGENERATE_FROM,
    /*
     * UPSTREAM CHURN, COUNTED RATHER THAN TYPED.
     *
     * Both numbers were prose in the acceptance evidence, which is the rot the
     * collector exists to stop: true the day they are typed and silently wrong
     * after the next fetch. Counted from the PRESERVED clone over the same range
     * the drill just rebased across, so the churn and the conflict surface can
     * never describe two different ranges.
     */
    upstreamChurn: {
      range: `${base.slice(0, 12)}..${target.slice(0, 12)}`,
      commits: countCommits(upstreamRoot, base, target),
      closureTouching: countCommits(upstreamRoot, base, target, closurePaths),
      closureFiles: closurePaths,
    },
    upstreamRoot,
    forkRoot,
    /** Neither real checkout moved. Asserted below rather than promised. */
    base,
    target,
    targetRef: onto,
    forkHead,
    commitsCarried: Number(carried),
    scratch: keep ? clone : null,
  };
} catch (error) {
  result = {
    outcome: 'could-not-run',
    reason: `the scratch clone could not be prepared: ${error.message ?? error}`,
    upstreamRoot, forkRoot, base, target, forkHead,
  };
} finally {
  if (!keep) rmSync(scratch, { recursive: true, force: true });
}

/*
 * THE WATERMARK, RE-CHECKED AGAINST A REAL NEW UPSTREAM MIGRATION.
 *
 * This is the check that replaces the first draft's "upstream must not have
 * reached 900". That was the wrong invariant: under a watermark migrator the
 * danger is not upstream taking our number, it is upstream's migrations being
 * SKIPPED because a high id shadowed them — and the schema then quietly stops
 * keeping up while the migrator logs that it is current.
 *
 * Codev's columns never enter `migrationEntries` and never touch
 * `effect_sql_migrations`, so the watermark is whatever upstream last ran. The
 * invariant is therefore: every migration upstream adds must have an id ABOVE
 * the watermark our base leaves.
 *
 * Phase 2 tested that with a synthetic migration. This tests it with the real
 * one upstream actually shipped in the meantime, which is the difference between
 * a mechanism that works and a mechanism that has worked.
 */
function migrationIds(root, ref) {
  const listed = tryRun(root, 'ls-tree', '--name-only', ref, `${MIGRATIONS_DIR}/`);
  if (!listed.ok) return null;
  const ids = new Set();
  for (const line of listed.out.trim().split('\n').filter(Boolean)) {
    const match = /\/(\d+)_[^/]*(?<!\.test)\.ts$/.exec(line);
    if (match) ids.add(Number(match[1]));
  }
  return [...ids].sort((a, b) => a - b);
}

const atBase = migrationIds(upstreamRoot, base);
const atTarget = migrationIds(upstreamRoot, target);
if (atBase === null || atTarget === null) {
  result.watermark = {
    checked: false,
    reason: `could not list ${MIGRATIONS_DIR} at one of the two refs. Not checked is not "checked `
      + 'and fine".',
  };
} else {
  const watermarkAtBase = atBase.length === 0 ? null : Math.max(...atBase);
  const added = atTarget.filter((id) => !atBase.includes(id));
  const shadowed = added.filter((id) => watermarkAtBase !== null && id <= watermarkAtBase);
  result.watermark = {
    checked: true,
    migrationsDir: MIGRATIONS_DIR,
    watermarkAtBase,
    addedByUpstream: added,
    shadowed,
    holds: shadowed.length === 0,
    detail: added.length === 0
      ? 'upstream added no migrations in this range, so the invariant had nothing to bite on. '
        + 'Reported rather than counted as a pass.'
      : shadowed.length === 0
        ? `upstream added ${added.join(', ')}, all above the watermark ${String(watermarkAtBase)} `
          + 'our base leaves — so they run. Codev writes nothing to effect_sql_migrations, which '
          + 'is what keeps that true.'
        : `upstream added ${shadowed.join(', ')} at or below the watermark `
          + `${String(watermarkAtBase)}. Those would be SKIPPED, silently.`,
  };
}

/*
 * THE READ-ONLY ORDER, CHECKED RATHER THAN ASSERTED.
 *
 * The whole design rests on neither real checkout moving, and a claim that is
 * only made in a comment is a claim nobody verifies. Both are re-read AFTER the
 * drill and compared to what they were before.
 */
const upstreamAfter = run(upstreamRoot, 'rev-parse', 'HEAD').trim();
const forkAfter = run(forkRoot, 'rev-parse', 'HEAD').trim();
const upstreamDirty = run(upstreamRoot, 'status', '--porcelain').trim() !== '';
const forkDirty = run(forkRoot, 'status', '--porcelain').trim() !== '';
result.preserved = {
  upstreamHead: upstreamAfter,
  upstreamStillAtBase: upstreamAfter === base,
  upstreamClean: !upstreamDirty,
  forkHead: forkAfter,
  forkUnmoved: forkAfter === forkHead,
  forkClean: !forkDirty,
  pinCommitUnchanged: JSON.parse(readFileSync(pinPath, 'utf8')).commit === pin.commit,
};
if (
  !result.preserved.upstreamStillAtBase
  || !result.preserved.forkUnmoved
  || !result.preserved.pinCommitUnchanged
) {
  result.outcome = 'could-not-run';
  result.reason = 'a real checkout moved during the drill. The result is discarded: a drill that '
    + 'disturbed the thing it was supposed to leave alone cannot be trusted about anything else.';
}

report(result);
