/**
 * Spec 146, Phase 3 — command ids and the dispatch journal.
 *
 * THE PROPERTY
 *
 * "Every command carries a `commandId` generated by porch and persisted before
 * dispatch, so a crash between dispatch and acknowledgement is recoverable
 * without duplicating work." The id is generated *here*, written to disk *here*,
 * and only then handed to the transport.
 *
 * WHY THE ORDER IS THE WHOLE FILE
 *
 * A crash has three possible positions and they are not equally survivable:
 *
 *  1. Before the journal write — nothing happened, nothing to recover.
 *  2. After the journal write, before dispatch — the intent exists, the command
 *     does not. Recovery re-dispatches it.
 *  3. After dispatch, before the acknowledgement is recorded — indistinguishable
 *     from (2) **from disk alone**, which is the point. Recovery re-dispatches
 *     with the SAME `commandId`, and the server's idempotency collapses the
 *     duplicate.
 *
 * Journalling after dispatch would make (3) invisible instead of ambiguous, and
 * an invisible ambiguity is a lost command.
 *
 * WHY A TORN LAST LINE IS NOT CORRUPTION
 *
 * The journal is append-only and each record is one line. A process killed
 * mid-write leaves a partial final line, which is expected and recoverable. A
 * partial line *anywhere else* is a damaged file, and answering both with "no
 * pending commands" would spell "I could not read this" exactly like "there is
 * nothing here" — so the second throws.
 *
 * **Tolerating the torn tail is not enough — it has to be removed.** The first
 * version of this file skipped it on read and appended after it, so the next
 * record was concatenated onto the partial line and became a corrupt line in the
 * MIDDLE of the file. From then on every read threw, and recovery was dead
 * permanently, one crash after the crash it was written to survive. So an append
 * truncates a torn tail first, and the truncation is recorded rather than done
 * quietly.
 */

import {
  closeSync,
  existsSync,
  fsyncSync,
  mkdirSync,
  openSync,
  readFileSync,
  writeFileSync,
  writeSync,
} from 'node:fs';
import { randomUUID } from 'node:crypto';
import { dirname } from 'node:path';

/** A command id. Generated by porch, never by the server. */
export function newCommandId(): string {
  return randomUUID();
}

/** Journal record kinds. `intent` precedes dispatch; `outcome` follows it. */
export type JournalRecord =
  | {
      readonly kind: 'intent';
      readonly commandId: string;
      readonly type: string;
      readonly command: unknown;
      /**
       * The CALLER's identity for this intent — a mailbox row id, a phase, whatever the
       * caller must be able to recognise it by after a restart.
       *
       * Not sent to the server and not part of the command: it exists so recovery can
       * answer "is this pending intent MINE" without guessing from the payload.
       * Matching on payload content is what this replaces, and it was wrong — two
       * identical messages to one agent (a retried instruction, a repeated nudge, any
       * templated notice) made a stale intent look like the current one, and recovery
       * would then report a message delivered that was never submitted. A duplicate turn
       * is visible and recoverable; a false "delivered" is neither.
       *
       * Optional because records written before it exists have none, and an absent ref
       * simply never matches — which is the safe direction.
       */
      readonly ref?: string;
      readonly at: string;
    }
  | {
      readonly kind: 'outcome';
      readonly commandId: string;
      readonly status: 'dispatched' | 'failed';
      readonly error?: string;
      readonly at: string;
    };

/**
 * The journal file was damaged in a way a crash does not produce.
 *
 * Distinct from an empty journal and from a torn tail, because those two are
 * ordinary and this one means a caller must not proceed as if it had read the
 * file.
 */
export class JournalCorruptError extends Error {
  constructor(
    readonly path: string,
    readonly line: number,
    readonly detail: string,
  ) {
    super(
      `Dispatch journal ${path} is damaged at line ${line}: ${detail}\n` +
        `  A crash leaves a partial LAST line, which is recovered silently. A ` +
        `partial line anywhere else is not something a crash produces, so it is ` +
        `reported rather than skipped — skipping it would report "nothing pending" ` +
        `for a file we could not read.`,
    );
    this.name = 'JournalCorruptError';
  }
}

export interface JournalReadResult {
  readonly records: ReadonlyArray<JournalRecord>;
  /** True when the final line was partial — a crash mid-append. */
  readonly tornTail: boolean;
}

/**
 * An append-only, fsynced record of what porch intended to dispatch.
 *
 * Every write is `write(2)` + `fsync(2)` on a fresh descriptor. That is slower
 * than buffering and it is the reason the journal is worth having: a record still
 * sitting in the page cache when the machine dies did not survive the crash it
 * exists for.
 */
export class DispatchJournal {
  constructor(readonly path: string) {
    mkdirSync(dirname(path), { recursive: true });
  }

  /**
   * Cut a partial final line off before appending.
   *
   * Returns what was discarded, so a caller can log it — a torn record is a
   * command whose intent was being written when the process died, and dropping it
   * silently would be the same class of loss the journal exists to prevent. (The
   * command itself is not lost: an intent that never finished being written also
   * never reached dispatch.)
   */
  #truncateTornTail(): string | null {
    if (!existsSync(this.path)) return null;
    const raw = readFileSync(this.path, 'utf-8');
    if (raw.length === 0 || raw.endsWith('\n')) return null;
    const lastNewline = raw.lastIndexOf('\n');
    const torn = raw.slice(lastNewline + 1);
    writeFileSync(this.path, lastNewline === -1 ? '' : raw.slice(0, lastNewline + 1));
    return torn;
  }

  #append(record: JournalRecord): void {
    this.#truncateTornTail();
    const fd = openSync(this.path, 'a');
    try {
      writeSync(fd, JSON.stringify(record) + '\n');
      fsyncSync(fd);
    } finally {
      closeSync(fd);
    }
  }

  /**
   * Record the intent to dispatch. **Call before dispatch, never after.**
   *
   * Returns once the bytes are on the device.
   */
  recordIntent(commandId: string, type: string, command: unknown, ref?: string): void {
    this.#append({
      kind: 'intent',
      commandId,
      type,
      command,
      ...(ref === undefined ? {} : { ref }),
      at: new Date().toISOString(),
    });
  }

  /** Record what happened to a dispatched command. */
  recordOutcome(commandId: string, status: 'dispatched' | 'failed', error?: string): void {
    this.#append({ kind: 'outcome', commandId, status, ...(error ? { error } : {}), at: new Date().toISOString() });
  }

  /**
   * Remove a torn final line, returning it.
   *
   * Called automatically before every append; exposed so a recovering caller can
   * report the repair instead of discovering the file had already been fixed.
   */
  repairTornTail(): string | null {
    return this.#truncateTornTail();
  }

  /** Every record in order, with the torn-tail fact kept rather than hidden. */
  read(): JournalReadResult {
    if (!existsSync(this.path)) return { records: [], tornTail: false };
    const raw = readFileSync(this.path, 'utf-8');
    if (raw.length === 0) return { records: [], tornTail: false };

    const lines = raw.split('\n');
    // A complete file ends with '\n', so the split leaves a trailing ''. Anything
    // else in that position is a line the crash cut in half.
    const trailing = lines.pop() ?? '';
    const tornTail = trailing.length > 0;

    const records: JournalRecord[] = [];
    lines.forEach((line, index) => {
      if (line.length === 0) return;
      try {
        records.push(JSON.parse(line) as JournalRecord);
      } catch (error) {
        throw new JournalCorruptError(this.path, index + 1, (error as Error).message);
      }
    });
    return { records, tornTail };
  }

  /**
   * Commands whose fate is unknown: an intent with no outcome.
   *
   * These are exactly the commands recovery re-dispatches — under their original
   * `commandId`, so a command that DID land is deduplicated by the server rather
   * than applied twice.
   */
  pending(): ReadonlyArray<Extract<JournalRecord, { kind: 'intent' }>> {
    const { records } = this.read();
    const settled = new Set<string>();
    for (const record of records) {
      if (record.kind === 'outcome') settled.add(record.commandId);
    }
    const seen = new Set<string>();
    const pending: Array<Extract<JournalRecord, { kind: 'intent' }>> = [];
    for (const record of records) {
      if (record.kind !== 'intent') continue;
      if (settled.has(record.commandId) || seen.has(record.commandId)) continue;
      seen.add(record.commandId);
      pending.push(record);
    }
    return pending;
  }
}

/**
 * Did the server answer, and answer no?
 *
 * `RpcFailureError` is the server's own failure Exit — a decision. Everything
 * else on this path (`NotConnectedError`, `RequestTimeoutError`, `ProtocolError`,
 * `MalformedFrameError`, anything unrecognised) means no answer arrived, and an
 * absent answer is not a negative one.
 *
 * Matched by `name` rather than `instanceof` so this module does not import the
 * transport's error classes, and so an error that crossed a realm still
 * classifies — the same reason `subscription.ts` matches by name.
 *
 * The default is deliberately "unanswered": a misclassified refusal costs one
 * redundant re-dispatch that the server deduplicates, while a misclassified
 * transport failure costs the command.
 */
export function isServerRefusal(error: unknown): boolean {
  return (error as { name?: unknown } | null)?.name === 'RpcFailureError';
}

/** What `dispatch` needs of a transport. Injected, so no socket is required to test it. */
export interface CommandDispatcher {
  call(method: string, payload: unknown): Promise<unknown>;
}

export const DISPATCH_METHOD = 'orchestration.dispatchCommand';

export interface DispatchOptions {
  /**
   * Run between the journal write and the dispatch.
   *
   * The crash window the spec names is exactly here, and a test that cannot
   * stand inside it can only simulate the crash. Production passes nothing.
   */
  readonly beforeDispatch?: () => void | Promise<void>;
  /**
   * Run between the dispatch returning and the outcome being journalled.
   *
   * The second window, and the ambiguous one: from disk it is indistinguishable
   * from the first, and recovery must handle it by re-dispatching under the same
   * `commandId` rather than by guessing which side of the line the crash fell on.
   */
  readonly afterDispatch?: (result: unknown) => void | Promise<void>;
  /**
   * The caller's identity for this intent, journalled alongside it.
   *
   * See {@link JournalRecord}'s `ref`. Never sent to the server.
   */
  readonly ref?: string;
}

/**
 * Journal, then dispatch, then record the outcome.
 *
 * `command` is sent as given except that `commandId` is set from the journalled
 * id: a caller that supplied its own id keeps it (recovery does), and a caller
 * that did not gets one generated here.
 */
export async function dispatchCommand(
  dispatcher: CommandDispatcher,
  journal: DispatchJournal,
  command: Record<string, unknown> & { type: string },
  options: DispatchOptions = {},
): Promise<{ readonly commandId: string; readonly result: unknown }> {
  const commandId = typeof command.commandId === 'string' ? command.commandId : newCommandId();
  const payload = { ...command, commandId };

  journal.recordIntent(commandId, command.type, payload, options.ref);
  await options.beforeDispatch?.();

  try {
    const result = await dispatcher.call(DISPATCH_METHOD, payload);
    await options.afterDispatch?.(result);
    journal.recordOutcome(commandId, 'dispatched');
    return { commandId, result };
  } catch (error) {
    // A REFUSAL is settled. An UNANSWERED command is not.
    //
    // These must not be journalled the same way. The server answering "no" is a
    // fact: re-dispatching it would replay a decision that was already made. A
    // socket that died, a request that timed out, a connection declared unusable
    // — none of those tell us whether the command landed, and recording them as
    // `failed` spells "I could not tell" exactly like "no", which is how a command
    // the server APPLIED gets dropped from recovery forever.
    //
    // So an unanswered command stays pending, and recovery re-dispatches it under
    // the same `commandId`. That is safe by construction: t3code keys a receipt on
    // `commandId` and returns the original result rather than applying twice
    // (`OrchestrationEngine.ts:142-169` at the pinned commit).
    if (isServerRefusal(error)) journal.recordOutcome(commandId, 'failed', (error as Error).message);
    throw error;
  }
}

/**
 * Re-dispatch every command whose outcome is unknown.
 *
 * Same ids, so the server collapses anything that already landed. Returns the
 * ids replayed, in journal order, because "nothing was pending" and "recovery
 * ran" must be distinguishable to the caller.
 *
 * Throws on the first replay that does not succeed, and what it writes before
 * throwing depends on WHICH kind of failure it was: a refusal is journalled
 * `failed` and settled, an unanswered command is left pending for the next
 * recovery. Re-running recovery after a transport failure therefore resumes from
 * the same intent rather than from a shorter list.
 */
export async function recoverPendingCommands(
  dispatcher: CommandDispatcher,
  journal: DispatchJournal,
): Promise<ReadonlyArray<string>> {
  const pending = journal.pending();
  const replayed: string[] = [];
  for (const intent of pending) {
    try {
      await dispatcher.call(DISPATCH_METHOD, intent.command);
      journal.recordOutcome(intent.commandId, 'dispatched');
    } catch (error) {
      // The SAME split `dispatchCommand` makes, and for a sharper reason.
      //
      // Recovery runs immediately after a crash, which is precisely when the
      // server may still be coming up: a dead socket here is the expected case,
      // not the exotic one. Journalling it `failed` gives the intent an outcome,
      // `pending()` stops returning it, and the command recovery exists to re-send
      // is dropped from recovery permanently — by the one code path whose entire
      // job is not to drop it.
      if (isServerRefusal(error)) journal.recordOutcome(intent.commandId, 'failed', (error as Error).message);
      throw error;
    }
    replayed.push(intent.commandId);
  }
  return replayed;
}
