/**
 * Spec 146, Phase 3 — command ids and the dispatch journal.
 *
 * THE PROPERTY
 *
 * "Every command carries a `commandId` generated by porch and persisted before
 * dispatch, so a crash between dispatch and acknowledgement is recoverable
 * without duplicating work." The id is generated *here*, written to disk *here*,
 * and only then handed to the transport.
 *
 * WHY THE ORDER IS THE WHOLE FILE
 *
 * A crash has three possible positions and they are not equally survivable:
 *
 *  1. Before the journal write — nothing happened, nothing to recover.
 *  2. After the journal write, before dispatch — the intent exists, the command
 *     does not. Recovery re-dispatches it.
 *  3. After dispatch, before the acknowledgement is recorded — indistinguishable
 *     from (2) **from disk alone**, which is the point. Recovery re-dispatches
 *     with the SAME `commandId`, and the server's idempotency collapses the
 *     duplicate.
 *
 * Journalling after dispatch would make (3) invisible instead of ambiguous, and
 * an invisible ambiguity is a lost command.
 *
 * WHY A TORN LAST LINE IS NOT CORRUPTION
 *
 * The journal is append-only and each record is one line. A process killed
 * mid-write leaves a partial final line, which is expected and recoverable. A
 * partial line *anywhere else* is a damaged file, and answering both with "no
 * pending commands" would spell "I could not read this" exactly like "there is
 * nothing here" — so the second throws.
 */

import { closeSync, existsSync, fsyncSync, mkdirSync, openSync, readFileSync, writeSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import { dirname } from 'node:path';

/** A command id. Generated by porch, never by the server. */
export function newCommandId(): string {
  return randomUUID();
}

/** Journal record kinds. `intent` precedes dispatch; `outcome` follows it. */
export type JournalRecord =
  | {
      readonly kind: 'intent';
      readonly commandId: string;
      readonly type: string;
      readonly command: unknown;
      readonly at: string;
    }
  | {
      readonly kind: 'outcome';
      readonly commandId: string;
      readonly status: 'dispatched' | 'failed';
      readonly error?: string;
      readonly at: string;
    };

/**
 * The journal file was damaged in a way a crash does not produce.
 *
 * Distinct from an empty journal and from a torn tail, because those two are
 * ordinary and this one means a caller must not proceed as if it had read the
 * file.
 */
export class JournalCorruptError extends Error {
  constructor(
    readonly path: string,
    readonly line: number,
    readonly detail: string,
  ) {
    super(
      `Dispatch journal ${path} is damaged at line ${line}: ${detail}\n` +
        `  A crash leaves a partial LAST line, which is recovered silently. A ` +
        `partial line anywhere else is not something a crash produces, so it is ` +
        `reported rather than skipped — skipping it would report "nothing pending" ` +
        `for a file we could not read.`,
    );
    this.name = 'JournalCorruptError';
  }
}

export interface JournalReadResult {
  readonly records: ReadonlyArray<JournalRecord>;
  /** True when the final line was partial — a crash mid-append. */
  readonly tornTail: boolean;
}

/**
 * An append-only, fsynced record of what porch intended to dispatch.
 *
 * Every write is `write(2)` + `fsync(2)` on a fresh descriptor. That is slower
 * than buffering and it is the reason the journal is worth having: a record still
 * sitting in the page cache when the machine dies did not survive the crash it
 * exists for.
 */
export class DispatchJournal {
  constructor(readonly path: string) {
    mkdirSync(dirname(path), { recursive: true });
  }

  #append(record: JournalRecord): void {
    const fd = openSync(this.path, 'a');
    try {
      writeSync(fd, JSON.stringify(record) + '\n');
      fsyncSync(fd);
    } finally {
      closeSync(fd);
    }
  }

  /**
   * Record the intent to dispatch. **Call before dispatch, never after.**
   *
   * Returns once the bytes are on the device.
   */
  recordIntent(commandId: string, type: string, command: unknown): void {
    this.#append({ kind: 'intent', commandId, type, command, at: new Date().toISOString() });
  }

  /** Record what happened to a dispatched command. */
  recordOutcome(commandId: string, status: 'dispatched' | 'failed', error?: string): void {
    this.#append({ kind: 'outcome', commandId, status, ...(error ? { error } : {}), at: new Date().toISOString() });
  }

  /** Every record in order, with the torn-tail fact kept rather than hidden. */
  read(): JournalReadResult {
    if (!existsSync(this.path)) return { records: [], tornTail: false };
    const raw = readFileSync(this.path, 'utf-8');
    if (raw.length === 0) return { records: [], tornTail: false };

    const lines = raw.split('\n');
    // A complete file ends with '\n', so the split leaves a trailing ''. Anything
    // else in that position is a line the crash cut in half.
    const trailing = lines.pop() ?? '';
    const tornTail = trailing.length > 0;

    const records: JournalRecord[] = [];
    lines.forEach((line, index) => {
      if (line.length === 0) return;
      try {
        records.push(JSON.parse(line) as JournalRecord);
      } catch (error) {
        throw new JournalCorruptError(this.path, index + 1, (error as Error).message);
      }
    });
    return { records, tornTail };
  }

  /**
   * Commands whose fate is unknown: an intent with no outcome.
   *
   * These are exactly the commands recovery re-dispatches — under their original
   * `commandId`, so a command that DID land is deduplicated by the server rather
   * than applied twice.
   */
  pending(): ReadonlyArray<Extract<JournalRecord, { kind: 'intent' }>> {
    const { records } = this.read();
    const settled = new Set<string>();
    for (const record of records) {
      if (record.kind === 'outcome') settled.add(record.commandId);
    }
    const seen = new Set<string>();
    const pending: Array<Extract<JournalRecord, { kind: 'intent' }>> = [];
    for (const record of records) {
      if (record.kind !== 'intent') continue;
      if (settled.has(record.commandId) || seen.has(record.commandId)) continue;
      seen.add(record.commandId);
      pending.push(record);
    }
    return pending;
  }
}

/** What `dispatch` needs of a transport. Injected, so no socket is required to test it. */
export interface CommandDispatcher {
  call(method: string, payload: unknown): Promise<unknown>;
}

export const DISPATCH_METHOD = 'orchestration.dispatchCommand';

export interface DispatchOptions {
  /**
   * Run between the journal write and the dispatch.
   *
   * The crash window the spec names is exactly here, and a test that cannot
   * stand inside it can only simulate the crash. Production passes nothing.
   */
  readonly beforeDispatch?: () => void | Promise<void>;
  /**
   * Run between the dispatch returning and the outcome being journalled.
   *
   * The second window, and the ambiguous one: from disk it is indistinguishable
   * from the first, and recovery must handle it by re-dispatching under the same
   * `commandId` rather than by guessing which side of the line the crash fell on.
   */
  readonly afterDispatch?: (result: unknown) => void | Promise<void>;
}

/**
 * Journal, then dispatch, then record the outcome.
 *
 * `command` is sent as given except that `commandId` is set from the journalled
 * id: a caller that supplied its own id keeps it (recovery does), and a caller
 * that did not gets one generated here.
 */
export async function dispatchCommand(
  dispatcher: CommandDispatcher,
  journal: DispatchJournal,
  command: Record<string, unknown> & { type: string },
  options: DispatchOptions = {},
): Promise<{ readonly commandId: string; readonly result: unknown }> {
  const commandId = typeof command.commandId === 'string' ? command.commandId : newCommandId();
  const payload = { ...command, commandId };

  journal.recordIntent(commandId, command.type, payload);
  await options.beforeDispatch?.();

  try {
    const result = await dispatcher.call(DISPATCH_METHOD, payload);
    await options.afterDispatch?.(result);
    journal.recordOutcome(commandId, 'dispatched');
    return { commandId, result };
  } catch (error) {
    // Recorded as failed so recovery does not re-dispatch a command the server
    // refused on its merits. A transport failure is the ambiguous case and is
    // recorded the same way on purpose: re-dispatch is idempotent, so the cost of
    // treating a refusal as settled is bounded, while re-dispatching a command
    // the server rejected loops forever.
    journal.recordOutcome(commandId, 'failed', (error as Error).message);
    throw error;
  }
}

/**
 * Re-dispatch every command whose outcome is unknown.
 *
 * Same ids, so the server collapses anything that already landed. Returns the
 * ids replayed, in journal order, because "nothing was pending" and "recovery
 * ran" must be distinguishable to the caller.
 */
export async function recoverPendingCommands(
  dispatcher: CommandDispatcher,
  journal: DispatchJournal,
): Promise<ReadonlyArray<string>> {
  const pending = journal.pending();
  const replayed: string[] = [];
  for (const intent of pending) {
    try {
      await dispatcher.call(DISPATCH_METHOD, intent.command);
      journal.recordOutcome(intent.commandId, 'dispatched');
    } catch (error) {
      journal.recordOutcome(intent.commandId, 'failed', (error as Error).message);
      throw error;
    }
    replayed.push(intent.commandId);
  }
  return replayed;
}
