/**
 * Builder phase stop-guard (Issue #41).
 *
 * ## The failure
 *
 * A builder ends its turn mid-phase with nothing blocking it, and nobody
 * notices until a human opens the pane — routinely hours. Two incidents, one
 * week apart, with the same shape. The second one's last message read:
 *
 *   - Phase 1 committed as e62d1c0; build and tests green
 *   - Moving to phase 2, the seam measurement harness
 *   - No action needed from you
 *
 * ...and then it did nothing. It was not confused about what to do next; it
 * named the next phase. It intended to continue.
 *
 * ## Why prompt wording cannot fix it
 *
 * **Writing a summary to the pane IS ending the turn.** The agentic loop runs
 * while the model emits tool calls and terminates at its first response that is
 * only prose. So "report, then keep working" cannot happen in that order —
 * reporting is the stop. The builder does not experience those as one act, and
 * no amount of instruction changes the mechanic, because the instruction is
 * itself read at the moment the model has already decided to write prose.
 *
 * Issue #40 rewrote porch's phase-handoff box and the builder role doc to say
 * this out loud, which makes the mistake harder. It cannot make it impossible:
 * documentation loads into context and can be read past. A Stop hook is
 * enforcement — the harness runs it whether or not the model remembers.
 *
 * ## Design, in order of how badly each would hurt if got wrong
 *
 *   1. FAILS OPEN, ALWAYS. Every error path allows the stop. A Stop hook that
 *      blocks on its own bug traps a builder in a loop it cannot talk its way
 *      out of. No failure mode here is worse than "the guard did nothing".
 *   2. NEVER BLOCKS A HUMAN GATE. Telling a builder parked at `dev-approval`
 *      to "do the next unit of work now" pushes it past a decision only a human
 *      may make. Any gate in `pending` allows the stop. When the guard cannot
 *      tell, it allows: a false "there is a gate" costs one un-nudged turn, a
 *      false "there is no gate" costs a bypassed gate.
 *   3. NUDGES ONCE, NEVER LOOPS. `stop_hook_active` is true when this hook has
 *      already blocked and the model is continuing because of it. Seeing that,
 *      allow. The shape is: stop -> one nudge -> work -> stop -> allowed. A
 *      genuine need to stop costs one extra turn, not an infinite fight.
 *
 * ## Why it reads status.yaml instead of shelling out to porch
 *
 * A prior hand-written version of this guard called `porch status` and grepped
 * its output for gate wording. It grepped for four phrases porch does not
 * print, so it matched nothing and would have nudged at every gate. Display
 * strings are a fragile contract between two programs. `status.yaml` is the
 * structured source, needs no subprocess, and does not change wording between
 * releases.
 *
 * @see codev/roles/builder.md — "A phase handoff is not a stopping point"
 */

import { isAbsolute, join, resolve } from 'node:path';

/** Worktree-relative path of the emitted guard script. */
export const STOP_GUARD_SCRIPT_RELPATH = '.claude/hooks/phase-stop-guard.cjs';

/**
 * Phases at which there is nothing left to drive.
 *
 * `verified` is porch's own terminal phase — `advanceProtocolPhase` sets it
 * when a protocol runs out of phases, and `state.ts` migrates the legacy
 * `complete` onto it. Omitting it earns every finished project one pointless
 * nudge.
 */
export const TERMINAL_PHASES = ['verified', 'complete', 'completed', 'done', 'cleanup', 'archived'];

/**
 * The self-contained Node guard script, emitted verbatim into each worktree.
 *
 * Kept as a string constant (not a separate asset) so it ships with the
 * compiled package automatically — `tsc` does not copy non-TS files to `dist`.
 * The unit test writes this constant to a temp `.cjs` and spawns it with
 * fixture stdin, so the constant is the tested artifact.
 *
 * Self-contained: Node core only. Worktrees have no access to the package's
 * node_modules, and neither do adopter repos. It also must not depend on `jq`
 * or a `porch` on PATH, both of which are absent on some adopter machines.
 */
export const PHASE_STOP_GUARD_SCRIPT = `#!/usr/bin/env node
// AUTO-GENERATED by @cluesmith/codev (Issue #41). Do not edit in the worktree;
// edit packages/codev/src/agent-farm/utils/phase-stop-guard.ts instead.
'use strict';

const fs = require('node:fs');
const path = require('node:path');

const TERMINAL_PHASES = new Set(${JSON.stringify(TERMINAL_PHASES)});

/** Allow the stop. Every failure path lands here. */
function allow() {
  process.exit(0);
}

function block(phase) {
  process.stdout.write(JSON.stringify({
    decision: 'block',
    reason: [
      'STOP BLOCKED — porch is still at phase "' + phase + '".',
      '',
      'You were about to end the turn while a protocol phase is open. If your last message ' +
      'stated a next action ("next I will...", "continuing with...", "starting X now"), that ' +
      'sentence became false the moment the turn ended: nothing of yours runs between user ' +
      'messages, so ending the turn IS going idle.',
      '',
      'Writing a summary to the pane is not a step you take before continuing — it IS the act ' +
      'of ending the turn. A turn runs while you emit tool calls and ends at your first ' +
      'message that is only prose. So "report, then keep working" cannot happen in that order.',
      '',
      'Do the next unit of work now, in THIS turn. Reporting is a side channel, never a ' +
      'handoff: \`afx send architect\` is a tool call and does not end your turn, and the ' +
      'architect cannot see porch state.',
      '',
      'Legitimate stops: a gate awaiting a human, a blocker you cannot act around, or protocol ' +
      'completion. If this is one of those, say which and stop again — this guard nudges once ' +
      'per cycle and will not block you twice.',
    ].join('\\n'),
  }));
  process.exit(0);
}

/**
 * Locate <root>/codev/projects/<id>-<slug>/status.yaml.
 *
 * The id is baked in at spawn time, but the slug is not, so this matches on the
 * id segment. Exact-match first: an id of "13" must not resolve to "1313-..."
 * (the zero-strip collision that bit artifact lookup in issue #9).
 */
function findStatusPath(root, projectId) {
  const projectsDir = path.join(root, 'codev', 'projects');
  let entries;
  try {
    entries = fs.readdirSync(projectsDir, { withFileTypes: true });
  } catch {
    return null;
  }
  const dirs = entries.filter((e) => e.isDirectory()).map((e) => e.name);
  const prefix = projectId + '-';
  const match = dirs.find((d) => d === projectId || d.startsWith(prefix));
  if (!match) return null;
  const p = path.join(projectsDir, match, 'status.yaml');
  return fs.existsSync(p) ? p : null;
}

/**
/**
 * Read \`phase\` and whether any gate is genuinely awaiting a human.
 *
 * A deliberately small line scanner rather than a YAML parser: this file has
 * no dependencies available to it, and status.yaml's shape is fixed by porch's
 * own writer. Anything it cannot understand returns nulls, which fail open.
 *
 * A GATE COUNTS AS WAITING ONLY WITH BOTH \`status: pending\` AND
 * \`requested_at\`. Scanning for \`pending\` alone made this guard a total no-op
 * in production: \`createInitialState\` (state.ts:228-231) pre-seeds EVERY gate
 * in the protocol as \`{ status: 'pending' }\` at project creation, before any
 * has been reached. So from the moment a project exists there is always a
 * pending gate, and the guard always allowed. BUGFIX has exactly one gate,
 * making it a no-op for that entire protocol; for SPIR, \`pr\` and
 * \`verify-approval\` sit pending through the whole of \`implement\` -- which is
 * where both reported incidents happened.
 *
 * 24 green tests did not notice, because the fixture was hand-typed rather
 * than produced by porch. Verified against a real committed status.yaml.
 *
 * \`requested_at\` is set only by \`requestGate\` (index.ts:608-609), and porch
 * itself uses exactly this pair to decide "WAITING FOR HUMAN APPROVAL"
 * (index.ts:383 and :1080). Matching porch's own predicate is the point: a
 * second definition of "waiting" is how the two drift apart.
 */
function readState(statusPath) {
  let text;
  try {
    text = fs.readFileSync(statusPath, 'utf8');
  } catch {
    return { phase: null, gatePending: null };
  }

  let phase = null;
  let gatePending = false;
  let inGates = false;

  // Per-gate accumulators: the two keys arrive on separate lines, so a gate is
  // only judged once its block ends.
  let curPending = false;
  let curRequested = false;
  const flush = () => {
    if (curPending && curRequested) gatePending = true;
    curPending = false;
    curRequested = false;
  };

  for (const line of text.split('\\n')) {
    const phaseMatch = /^phase:\\s*['"]?([A-Za-z0-9_-]+)['"]?\\s*$/.exec(line);
    if (phaseMatch) phase = phaseMatch[1];

    if (/^gates:\\s*$/.test(line)) { inGates = true; continue; }
    // Any column-0 key ends the gates block.
    if (inGates && /^\\S/.test(line)) { flush(); inGates = false; }
    if (!inGates) continue;

    // A new gate name (two-space indent, bare key) closes the previous one.
    if (/^ {2}[^\\s#][^:]*:\\s*$/.test(line)) { flush(); continue; }
    if (/^\\s+status:\\s*['"]?pending['"]?\\s*$/.test(line)) curPending = true;
    if (/^\\s+requested_at:\\s*\\S/.test(line)) curRequested = true;
  }
  flush();

  return { phase, gatePending };
}

let raw = '';
process.stdin.on('data', (c) => { raw += c; });
process.stdin.on('end', () => {
  try {
    let input;
    try {
      input = JSON.parse(raw);
    } catch {
      return allow();
    }

    // Already nudged this cycle — let the model stop.
    if (input && input.stop_hook_active === true) return allow();

    const root = process.env.CODEV_WORKTREE_ROOT;
    const projectId = process.env.CODEV_PROJECT_ID;
    if (!root || !projectId) return allow();

    const statusPath = findStatusPath(root, projectId);
    if (!statusPath) return allow();

    const { phase, gatePending } = readState(statusPath);
    if (!phase) return allow();
    if (TERMINAL_PHASES.has(phase)) return allow();

    // A gate awaiting a human is a legitimate stop, and so is "I could not
    // tell" — gatePending is null only when the file could not be read.
    if (gatePending !== false) return allow();

    return block(phase);
  } catch {
    allow();
  }
});
`;

/** Single-quote-escape a value for safe embedding in a POSIX shell command. */
function shellSingleQuote(value: string): string {
  return value.replace(/'/g, `'\\''`);
}

/**
 * Build the shell command that runs the stop-guard for a builder worktree.
 *
 * The worktree root and project id are baked in rather than detected at run
 * time: the hook runs in whatever cwd the session happens to be in, and a guard
 * that guesses its own project is a guard that can nudge the wrong one.
 */
export function buildPhaseStopGuardCommand(worktreePath: string, projectId: string): string {
  const root = isAbsolute(worktreePath) ? worktreePath : resolve(worktreePath);
  const scriptAbs = join(root, STOP_GUARD_SCRIPT_RELPATH);
  return (
    `CODEV_WORKTREE_ROOT='${shellSingleQuote(root)}' ` +
    `CODEV_PROJECT_ID='${shellSingleQuote(projectId)}' ` +
    `node '${shellSingleQuote(scriptAbs)}'`
  );
}
