/**
 * Builder worktree write-guard (Issue #1018).
 *
 * A strict-mode builder runs in a git worktree nested inside the main checkout.
 * The Write/Edit tools require absolute paths, so the model must *synthesize*
 * one. When the runtime anchors that path at the inferred canonical repo root
 * instead of the worktree cwd, the `.builders/<id>/` segment is dropped and the
 * write silently lands in the main checkout (a real, writable, byte-identical
 * sibling tree). Instructions/memory don't hold against this because it's
 * intrinsic path-synthesis behavior that drifts across model/CLI upgrades — only
 * a deterministic guard holds.
 *
 * This module is the single source of truth for the guard. It emits two files
 * into each Claude builder worktree at spawn time (via CLAUDE_HARNESS):
 *   - `.claude/hooks/worktree-write-guard.cjs` — a self-contained Node hook
 *   - `.claude/settings.local.json` — a PreToolUse hook wiring on Write/Edit
 *
 * The hook denies any absolute Write/Edit path that resolves outside the
 * worktree root, with an allowlist for temp dirs and `$HOME/.claude` (so builder
 * memory/config writes still work). The worktree root is baked into the hook
 * command as `CODEV_WORKTREE_ROOT` (deterministic), with `git rev-parse
 * --show-toplevel` as a runtime fallback.
 *
 * @see codev/plans/1018-builder-worktree-write-guard-p.md
 */

import { isAbsolute, join, resolve } from 'node:path';
// Imported from the leaf module, NOT from porch/state.js: state.ts promisifies
// `execFile` at module load, and reaching it from here broke 24 doctor tests
// (its partial `node:child_process` mock has no `execFile`). See project-id.ts.
import { detectProjectIdFromCwd } from '../../commands/porch/project-id.js';
import {
  STOP_GUARD_SCRIPT_RELPATH,
  PHASE_STOP_GUARD_SCRIPT,
  buildPhaseStopGuardCommand,
} from './phase-stop-guard.js';

/** Worktree-relative path of the emitted guard script. */
export const GUARD_SCRIPT_RELPATH = '.claude/hooks/worktree-write-guard.cjs';

/** Worktree-relative path of the emitted settings file. */
export const GUARD_SETTINGS_RELPATH = '.claude/settings.local.json';

/**
 * The self-contained Node guard script, emitted verbatim into each worktree.
 *
 * Kept as a string constant (not a separate asset) so it ships with the
 * compiled package automatically — `tsc` does not copy non-TS files to `dist`.
 * It is exercised directly by the unit test, which writes it to a temp `.cjs`
 * and spawns it with fixture stdin, so the constant is the tested artifact.
 *
 * Self-contained: no `require` of any project code (worktrees have no access to
 * the package's node_modules, and neither do adopter repos). Node core only.
 *
 * Fail-open by design: any error (bad JSON, missing root, unexpected shape)
 * allows the tool call. A safety net must never brick a builder session; the
 * worst case of a failure is reverting to today's unguarded behavior.
 */
export const WORKTREE_WRITE_GUARD_SCRIPT = `#!/usr/bin/env node
// AUTO-GENERATED by @cluesmith/codev (Issue #1018). Do not edit in the worktree;
// edit packages/codev/src/agent-farm/utils/worktree-write-guard.ts instead.
'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { execSync } = require('node:child_process');

// Tools whose file_path we guard. NotebookEdit (notebook_path) is out of scope.
const GUARDED_TOOLS = new Set(['Write', 'Edit', 'MultiEdit']);

function allow() {
  process.exit(0);
}

function deny(target, root) {
  const reason =
    'Blocked: ' + target + ' is outside this builder\\'s worktree (' + root + '). ' +
    'Builders are isolated to their worktree — a path anchored at the main checkout ' +
    'root silently pollutes it. Re-root the path under ' + root +
    ' (prefer a worktree-relative path). Allowed exceptions: temp dirs and ~/.claude.';
  process.stdout.write(JSON.stringify({
    hookSpecificOutput: {
      hookEventName: 'PreToolUse',
      permissionDecision: 'deny',
      permissionDecisionReason: reason,
    },
  }));
  process.exit(0);
}

// Resolve a path to a canonical absolute form WITHOUT requiring it to exist:
// realpath the longest existing ancestor (resolving symlinks, e.g. macOS
// /tmp -> /private/tmp), then re-append the non-existent tail.
function canonicalize(p, cwd) {
  let abs = path.isAbsolute(p) ? p : path.resolve(cwd, p);
  abs = path.normalize(abs);
  let tail = '';
  let cur = abs;
  for (;;) {
    try {
      const real = fs.realpathSync(cur);
      return tail ? path.join(real, tail) : real;
    } catch (e) {
      const parent = path.dirname(cur);
      if (parent === cur) {
        return abs;
      }
      tail = tail ? path.join(path.basename(cur), tail) : path.basename(cur);
      cur = parent;
    }
  }
}

function isInside(child, parent) {
  if (!parent) {
    return false;
  }
  if (child === parent) {
    return true;
  }
  return child.startsWith(parent + path.sep);
}

function main(raw) {
  let input;
  try {
    input = JSON.parse(raw);
  } catch (e) {
    return allow();
  }

  const toolName = input && input.tool_name;
  if (!GUARDED_TOOLS.has(toolName)) {
    return allow();
  }

  const toolInput = (input && input.tool_input) || {};
  const filePath = toolInput.file_path;
  if (!filePath || typeof filePath !== 'string') {
    return allow();
  }

  const cwd = (input && input.cwd) || process.cwd();

  // Worktree root: baked-in env (deterministic) first, then git as a fallback.
  let root = process.env.CODEV_WORKTREE_ROOT;
  if (!root) {
    try {
      root = execSync('git rev-parse --show-toplevel', { cwd, encoding: 'utf8' }).trim();
    } catch (e) {
      root = '';
    }
  }
  if (!root) {
    // Can't determine the boundary — fail open rather than block every write.
    return allow();
  }
  root = canonicalize(root, cwd);

  const target = canonicalize(filePath, cwd);

  if (isInside(target, root)) {
    return allow();
  }

  // Allowlist: temp dirs (scratch) and ~/.claude (builder memory + config).
  const allowRoots = [];
  const addAllow = (p) => {
    if (p) {
      allowRoots.push(canonicalize(p, cwd));
    }
  };
  addAllow('/tmp');
  addAllow('/private/tmp');
  addAllow(process.env.TMPDIR);
  if (process.env.HOME) {
    addAllow(path.join(process.env.HOME, '.claude'));
  }

  for (const a of allowRoots) {
    if (isInside(target, a)) {
      return allow();
    }
  }

  return deny(target, root);
}

let buf = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', (d) => {
  buf += d;
});
process.stdin.on('end', () => {
  try {
    main(buf);
  } catch (e) {
    // Never brick a session on an unexpected error.
    allow();
  }
});
`;

/** Single-quote-escape a value for safe embedding in a POSIX shell command. */
function shellSingleQuote(value: string): string {
  return value.replace(/'/g, `'\\''`);
}

/**
 * Build the worktree files that install the write-guard for a Claude builder.
 *
 * @param worktreePath absolute path to the builder's worktree
 * @returns files (relativePath + content) for writeWorktreeFiles()
 */
export function buildWorktreeGuardFiles(
  worktreePath: string,
): Array<{ relativePath: string; content: string }> {
  const root = isAbsolute(worktreePath) ? worktreePath : resolve(worktreePath);
  const scriptAbs = join(root, GUARD_SCRIPT_RELPATH);

  // Bake the worktree root in (deterministic) and run via `node` so the emitted
  // script needs no executable bit.
  const command =
    `CODEV_WORKTREE_ROOT='${shellSingleQuote(root)}' ` +
    `node '${shellSingleQuote(scriptAbs)}'`;

  // Issue #41: the phase stop-guard rides in the same settings file. Two
  // writers of one file is how one of them silently loses, so this function
  // stays the single owner of `.claude/settings.local.json`.
  //
  // The project id comes from the worktree path via porch's OWN detector, not a
  // second copy of the rule. A guard that disagrees with porch about which
  // project it is watching would nudge about the wrong one. When the path is
  // not a recognized builder worktree the id is null and the Stop hook is
  // simply not installed — fail open, like every other path in these guards.
  const projectId = detectProjectIdFromCwd(root);

  const files: Array<{ relativePath: string; content: string }> = [
    { relativePath: GUARD_SCRIPT_RELPATH, content: WORKTREE_WRITE_GUARD_SCRIPT },
  ];

  const settings: {
    hooks: {
      PreToolUse: Array<{ matcher: string; hooks: Array<{ type: string; command: string }> }>;
      Stop?: Array<{ hooks: Array<{ type: string; command: string }> }>;
    };
  } = {
    hooks: {
      PreToolUse: [
        {
          matcher: 'Write|Edit|MultiEdit',
          hooks: [{ type: 'command', command }],
        },
      ],
    },
  };

  if (projectId) {
    settings.hooks.Stop = [
      {
        hooks: [{ type: 'command', command: buildPhaseStopGuardCommand(root, projectId) }],
      },
    ];
    files.push({ relativePath: STOP_GUARD_SCRIPT_RELPATH, content: PHASE_STOP_GUARD_SCRIPT });
  }

  files.push({
    relativePath: GUARD_SETTINGS_RELPATH,
    content: JSON.stringify(settings, null, 2) + '\n',
  });

  return files;
}
