/**
 * Tests for persistent consultation output paths (#512).
 *
 * Verifies that consultation output is written to persistent project
 * directory paths rather than relying on temp files that get cleaned up.
 */

import { describe, it, expect } from 'vitest';
import { _computePersistentOutputPath as computePersistentOutputPath } from '../index.js';

describe('computePersistentOutputPath', () => {
  it('generates correct path for numeric project ID', () => {
    const state = {
      id: '0042',
      title: 'feature-name',
      currentPlanPhase: null,
      phase: 'specify',
      iteration: 1,
      projectDir: '/workspace/codev/projects/0042-feature-name',
    };

    const result = computePersistentOutputPath(state, 'gemini');
    expect(result).toBe('/workspace/codev/projects/0042-feature-name/0042-specify-iter1-gemini.txt');
  });

  it('generates correct path for bugfix project ID', () => {
    const state = {
      id: 'bugfix-512',
      title: 'consultation-output-files-dele',
      currentPlanPhase: null,
      phase: 'fix',
      iteration: 1,
      projectDir: '/workspace/codev/projects/bugfix-512-consultation-output-files-dele',
    };

    const result = computePersistentOutputPath(state, 'codex');
    expect(result).toBe(
      '/workspace/codev/projects/bugfix-512-consultation-output-files-dele/bugfix-512-fix-iter1-codex.txt'
    );
  });

  it('uses currentPlanPhase when available', () => {
    const state = {
      id: '0042',
      title: 'feature-name',
      currentPlanPhase: 'phase_2',
      phase: 'implement',
      iteration: 3,
      projectDir: '/workspace/codev/projects/0042-feature-name',
    };

    const result = computePersistentOutputPath(state, 'claude');
    expect(result).toBe('/workspace/codev/projects/0042-feature-name/0042-phase_2-iter3-claude.txt');
  });

  it('falls back to phase when currentPlanPhase is null', () => {
    const state = {
      id: '0042',
      title: 'feature-name',
      currentPlanPhase: null,
      phase: 'review',
      iteration: 2,
      projectDir: '/workspace/codev/projects/0042-feature-name',
    };

    const result = computePersistentOutputPath(state, 'gemini');
    expect(result).toBe('/workspace/codev/projects/0042-feature-name/0042-review-iter2-gemini.txt');
  });

  it('path matches porch findReviewFiles pattern', () => {
    // This test ensures the path generated by computePersistentOutputPath
    // matches the pattern that porch's findReviewFiles() expects:
    //   <projectDir>/<id>-<phase>-iter<N>-<model>.txt
    const state = {
      id: '0073',
      title: 'my-feature',
      currentPlanPhase: 'phase_1',
      phase: 'implement',
      iteration: 1,
      projectDir: '/workspace/codev/projects/0073-my-feature',
    };

    for (const model of ['gemini', 'codex', 'claude', 'hermes', 'opencode']) {
      const result = computePersistentOutputPath(state, model);
      const fileName = result.split('/').pop()!;
      // Must match: <id>-<phase>-iter<N>-<model>.txt
      expect(fileName).toMatch(/^0073-phase_1-iter1-(gemini|codex|claude|hermes|opencode)\.txt$/);
    }
  });
});
